# Location of top-level MicroPython directory
MPY_DIR = $(HOME)/github/micropython

# Name of module
MOD = sha512

# Source files (.c or .py)
SRC = main.c sha512.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = armv7m


# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk 
